server:
  port: 9000
spring:
  datasource:
    url: ${vcap.services.wowe.credentials.jdbcUrl}
    username: ${vcap.services.wowe.credentials.username}
    password: ${vcap.services.wowe.credentials.password}
#    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mbste.model
  configuration:
    map-underscore-to-camel-case: true



#jdbc:mysql://us-cdbr-iron-east-05:
#  cleardb:
#    net/ad_906f14f87b0cf2e?user=be8a60b49eb0b7&password=5a3643bc:
#      name:ad_906f14f87b0cf2e
#      username: be8a60b49eb0b7
#        password:5a3643bc
#    mysql://be8a60b49eb0b7:5a3643bc@us-cdbr-iron-east-05:
#      cleardb:
#        net:3306/ad_906f14f87b0cf2e?reconnect=true:
#
#
#          jdbc:mysql://us-cdbr-iron-east-05:
#            cleardb:
#              net/ad_906f14f87b0cf2e?user=be8a60b49eb0b7&password=5a3643bc:
#  ad_906f14f87b0cf2e
