server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wowe?useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mbste.model
  configuration:
    map-underscore-to-camel-case: true

